
0: T -> (node -v and npm -v).
1: T -> npm install  (to install dependencies).
2: T -> node install  (ensure Node.js is properly installed).
3: T -> npm install -g @angular/cli (install Angular CLI globally).
4: T -> ng new name_your_project (create a new Angular project).
5: T -> cd name_your_project (navigate into the project folder).
6: T -> npm start 
7: T -> ng serve (compile and start the project).
8: T -> got to http://localhost:4200/  (to view your app).